#!/bin/bash

mkdir lab0
cd lab0
mkdir -p glameow8 hitmonchan6 togekiss6
echo -e "Развитые способности  Compoundeyes" > dustox3
echo -e "Способности\nBlaze Flash Fire Flame Body" > flareon6
echo -e "Возможности  Overland=3 Surface=14\nUnderwater=12 Jump=5 Power=4 Intelligence=4\nGilled=0" > sharpedo9
cd glameow8
mkdir -p accelgor venipede
echo -e "Возможности  Overland=7 Surface=7\nUnderwater=5 Jump=1 Power=4 Intelligence=4\nGroundshaper=0" > crustle
echo -e "Живет  Cave Taiga Tundra" > vanillite
echo -e "Развитые\nспособности  Sap Sipper" > leafeon
cd ../hitmonchan6
mkdir -p blissey seedot deerling
cd ../togekiss6
mkdir -p cranidos dusclops
echo -e "Способности  Swarm Torrent Swift Swim\nUnaware" > surskit
echo -e "satk=9 sdef=7 spd=7" > pelipper
echo -e "Тип диеты  Herbivore" > vespiquen

cd ../glameow8
chmod u=rx,g=rwx,o=rwx accelgor
chmod u=rw,g=r,o= crustle
chmod 660 vanillite
chmod 571 venipede
chmod u=,g=rw,o=w leafeon
cd ../hitmonchan6
chmod u=rwx,g=rx,o=wx blissey
chmod u=wx,g=rw,o=wx seedot
chmod u=rx,g=rwx,o=rwx deerling
cd ../togekiss6
chmod u=rwx,g=wx,o=rwx cranidos
chmod u=r,g=r,o= surskit
chmod u=,g=rw,o= pelipper
chmod 664 vespiquen
chmod 355 dusclops
cd ..
chmod u=r,g=r,o= dustox3
chmod u=,g=rw,o=w flareon6
chmod u=wx,g=x,o=x glameow8
chmod u=rwx,g=wx,o=rw hitmonchan6
chmod 440 sharpedo9
chmod 570 togekiss6

chmod u+r glameow8
chmod u+r glameow8/leafeon
cat togekiss6/surskit glameow8/leafeon > flareon6_86
chmod u-r glameow8/leafeon
chmod u-r glameow8
cat sharpedo9 > glameow8/leafeonsharpedo
ln -s glameow8 Copy_90
chmod u+w togekiss6
ln -s ../dustox3 togekiss6/vespiquendustox
chmod u-w togekiss6
chmod u+r glameow8
chmod u+w hitmonchan6/deerling
chmod u+r glameow8/leafeon
cp -r glameow8 hitmonchan6/deerling
chmod u-r glameow8/leafeon
chmod u-w hitmonchan6/deerling
chmod u-r glameow8
chmod u+w glameow8/accelgor
cp sharpedo9 glameow8/accelgor
chmod u-w glameow8/accelgor
chmod u+w togekiss6
ln sharpedo9 togekiss6/surskitsharpedo
chmod u-w togekiss6

chmod u+r glameow8
chmod u+r hitmonchan6/seedot
chmod u+r togekiss6/dusclops
ls -lR
chmod u-r glameow8
chmod u-r hitmonchan6/seedot
chmod u-r togekiss6/dusclops

wc -m flareon6 1>/tmp/answer368696 2>/tmp/errors368696
ls -lR 2>/dev/null | grep "^[-d]" | grep on | sort -nk5 | head -n3
cat togekiss6/* 2>/dev/null | grep ce
cat -n glameow8/vanillite glameow8/leafeon togekiss6/surskit togekiss6/pelipper | sort -rk2
cat flareon6 2>/tmp/errors368696 | grep e$
grep e$ flareon6 2>/tmp/errors368696
grep -rnh --include \*t "" ./ | sort -t : -k2 2>&1

rm -f flareon6
chmod u+w togekiss6
rm -f togekiss6/surskit
chmod u-w togekiss6
chmod u+w togekiss6
rm -f togekiss6/vespiquendustox
chmod u-w togekiss6
chmod u+w togekiss6
rm -f togekiss6/surskitsharpedo
chmod u-w togekiss6
chmod u+w togekiss6
rmdir togekiss6/cranidos
chmod u-w togekiss6
chmod u+w togekiss6
chmod u+r togekiss6/dusclops
rm -rf togekiss6
